POST http://localhost:3333/servico/RealizarCompra 
Content-Type: application/json

{
  "id_fornecedor" : 1, "id_estoque" : 1, "id_filial" : 1,
  "compra" : [
    {"id_produto" : 1, "quantidade" : 4, "valor_unitario" : 17.50},
    {"id_produto" : 2, "quantidade" : 4, "valor_unitario" : 17.50},
    {"id_produto" : 1, "quantidade" : 4, "valor_unitario" : 17.50},
    {"id_produto" : 1, "quantidade" : 4, "valor_unitario" : 17.50}
     ]
}


###
POST http://localhost:3333/servico/RealizarVenda
Content-Type: application/json

{
  "id_filial" : 1, "id_estoque" : 1,
  "venda" : [
     {"id_produto" : 1,  "nome_item" : "Bijuteria 1", "quantidade" : 1, "valor_unitario" : 17.50},
    {"id_produto" : 2, "nome_item" : "Relogio 1", "quantidade" : 1, "valor_unitario" : 17.50}
  ]
}


###

POST http://localhost:3333/servico/ConsumoInterno
Content-Type: application/json

{
  "id_filial" : 1, "id_estoque" : 1,
  "consumo_interno" : [
     {"id_produto" : 1, "quantidade" : 1},
     {"id_produto" : 1, "quantidade" : 1}
  ]
}
###

POST http://localhost:3333/servico/Perda
Content-Type: application/json

{
  "id_filial" : 1,
  "motivo" : "O servico estava parado a muito tempo no estoque e foi perdido",
  "itens" : [
     {"id_produto" : 1, "quantidade" : 3},
     {"id_produto" : 1, "quantidade" : 2}
  ]
}

###

POST http://localhost:3333/servico/Devolucao
Content-Type: application/json

{
  "id_filial" : 1,
  "motivo" : "Nao gostei do produto",
  "itens" : [
     {"id_produto" : 1, "quantidade" : 3},
     {"id_produto" : 1, "quantidade" : 2}
  ]
}

###

POST http://localhost:3333/servico/Ajuste

###

GET http://localhost:3333/servico/ListarDepositos/1
 
###

